# Example of re-expansion of the H₂CO PES using identical internal coordinate system

Here, we test expansion of the PES for formaldehyde molecule using different types of internal coordinates

In [1]:
import jax
import jax.numpy as jnp
import numpy as np

from vibrojet.basis_utils import generate_prod_ind
from vibrojet.potentials import h2co_AYTY
from vibrojet.taylor import deriv_list

jax.config.update("jax_enable_x64", True)

### Expand PES using the following coordinates:
- $y_1=1-\exp[-(r_{CO}-r_{CO}^{eq}(\tau))]$
- $y_2=1-\exp[-(r_{CH_1}-r_{CH_1}^{eq}(\tau))]$
- $y_3=1-\exp[-(r_{CH_2}-r_{CH_2}^{eq}(\tau))]$
- $y_4=\alpha_{\angle OCH_1}-\alpha_{\angle OCH_1}^{eq}(\tau)$
- $y_5=\alpha_{\angle OCH_2}-\alpha_{\angle OCH_2}^{eq}(\tau)$
- $y_6 = \cos(\tau)+1$

The equilibrium values of internal coordinates $r_{CO}^{eq}(\tau)$, ..., $\alpha_{\angle OCH_2}^{eq}(\tau)$ as functions of the dihedral *book* angle $\tau$ or $\cos(\tau)$ are calculated by function `h2co_AYTY.mep(tau)` or `h2co_AYTY.mep(cos_tau, if_costau=True)`, respectively.

In [2]:
def internal_to_y(q):
    r0, r1, r2, a1, a2, cos_tau = q
    r0eq, r1eq, r2eq, a1eq, a2eq, _ = h2co_AYTY.mep(cos_tau, if_costau=True)
    y1 = 1 - jnp.exp(-(r0 - r0eq))
    y2 = 1 - jnp.exp(-(r1 - r1eq))
    y3 = 1 - jnp.exp(-(r2 - r2eq))
    y4 = a1 - a1eq
    y5 = a2 - a2eq
    y6 = 1 + cos_tau
    return jnp.array([y1, y2, y3, y4, y5, y6])


def y_to_internal(y):
    y1, y2, y3, y4, y5, y6 = y
    cos_tau = y6 - 1
    r0eq, r1eq, r2eq, a1eq, a2eq, _ = h2co_AYTY.mep(cos_tau, if_costau=True)
    r0 = -jnp.log(1 - y1) + r0eq
    r1 = -jnp.log(1 - y2) + r1eq
    r2 = -jnp.log(1 - y3) + r2eq
    a1 = y4 + a1eq
    a2 = y5 + a2eq
    return jnp.array([r0, r1, r2, a1, a2, cos_tau])

Generate expansion for PES

In [3]:
ncoo = 6

max_pow = 6
powers = [np.arange(max_pow + 1)] * ncoo
deriv_ind, deriv_mind = next(
    generate_prod_ind(powers, select=lambda ind: np.sum(ind) <= max_pow)
)

print("max expansion power:", max_pow)
print("number of expansion terms:", len(deriv_ind))

tau0 = np.pi  # equilibrium value of the `book` dihedral angle
cos_tau0 = np.cos(tau0)

q0 = h2co_AYTY.mep(cos_tau0, if_costau=True)
y0 = internal_to_y(q0)

print("equilibrium values of r-alpha-costau coordinates:", q0)
print("equilibrium values of morse-dalpha-dcostau coordinates:", y0)

poten_coefs = deriv_list(
    lambda x: h2co_AYTY.poten(y_to_internal(x), if_costau=True),
    deriv_ind,
    y0,
    if_taylor=True,
)

max expansion power: 6
number of expansion terms: 924
equilibrium values of r-alpha-costau coordinates: [ 1.2   1.1   1.1   2.13  2.13 -1.  ]
equilibrium values of morse-dalpha-dcostau coordinates: [0. 0. 0. 0. 0. 0.]
Time for d= 0 : 11.71 s
Time for d= 1 : 11.8 s
Time for d= 2 : 22.98 s
Time for d= 3 : 37.41 s
Time for d= 4 : 57.16 s
Time for d= 5 : 79.4 s
Time for d= 6 : 105.73 s


Print computed coefficients and compare with the original PES expansion coefficients, with which they must agree

In [4]:
thresh = 1e-6
max_diff = 0
for i in range(len(deriv_ind)):
    if np.abs(poten_coefs[i] > thresh):
        ind = np.where((h2co_AYTY.ind == deriv_ind[i]).all(axis=1))[0][0]
        coef = h2co_AYTY.coefs[ind]
        diff = poten_coefs[i] - coef
        max_diff = max(max_diff, diff)
        print(
            deriv_ind[i],
            "%20.6f" % poten_coefs[i],
            "%20.6f" % coef,
            "%20.6f" % diff,
        )
print("max difference:", max_diff)

[0 0 0 0 0 1]         13239.727881         13239.727881             0.000000
[0 0 0 0 0 2]          4627.962169          4627.962169             0.000000
[0 0 0 0 0 3]          1439.478742          1439.478742             0.000000
[0 0 0 0 0 4]          1006.758455          1006.758455             0.000000
[0 0 0 0 2 0]         31402.651686         31402.651686             0.000000
[0 0 0 0 4 0]           463.426455           463.426455             0.000000
[0 0 0 1 1 0]         21264.254862         21264.254862             0.000000
[0 0 0 1 1 2]          8603.647823          8603.647823             0.000000
[0 0 0 1 2 0]         15666.762364         15666.762364             0.000000
[0 0 0 1 2 1]          6946.931759          6946.931759             0.000000
[0 0 0 1 3 0]          3284.199296          3284.199296             0.000000
[0 0 0 1 3 1]          1844.137939          1844.137939             0.000000
[0 0 0 1 4 0]          2960.387858          2960.387858             0.000000

### Expand PES using internal coordinates:
- $r_1=r_{CO}-r_{CO}^{eq}(\pi)$
- $r_2=r_{CH_1}-r_{CH_1}^{eq}(\pi)$
- $r_3=r_{CH_2}-r_{CH_2}^{eq}(\pi)$
- $\alpha_1=\alpha_{\angle OCH_1}-\alpha_{\angle OCH_1}^{eq}(\pi)$
- $\alpha_2=\alpha_{\angle OCH_2}-\alpha_{\angle OCH_2}^{eq}(\pi)$
- $\tau-\pi$

Generate expansion for PES

In [5]:
ncoo = 6

max_pow = 6
powers = [np.arange(max_pow + 1)] * ncoo
deriv_ind, deriv_mind = next(
    generate_prod_ind(powers, select=lambda ind: np.sum(ind) <= max_pow)
)

print("max expansion power:", max_pow)
print("number of expansion terms:", len(deriv_ind))

tau0 = np.pi  # equilibrium value of the `book` dihedral angle

q0 = h2co_AYTY.mep(tau0)

print("equilibrium values of r-alpha-tau coordinates:", q0)

poten_coefs = deriv_list(h2co_AYTY.poten, deriv_ind, q0, if_taylor=True)

max expansion power: 6
number of expansion terms: 924
equilibrium values of r-alpha-tau coordinates: [1.2        1.1        1.1        2.13       2.13       3.14159265]
Time for d= 0 : 11.41 s
Time for d= 1 : 11.66 s
Time for d= 2 : 22.38 s
Time for d= 3 : 36.88 s
Time for d= 4 : 55.19 s
Time for d= 5 : 76.98 s
Time for d= 6 : 104.12 s


Print coefficients

In [6]:
thresh = 1e-6
for i in range(len(deriv_ind)):
    if np.abs(poten_coefs[i] > thresh):
        print(deriv_ind[i], "%20.6f" % poten_coefs[i])

[0 0 0 0 0 2]          6619.863941
[0 0 0 0 0 4]           876.263322
[0 0 0 0 1 2]          4277.619516
[0 0 0 0 2 0]         31402.651686
[0 0 0 0 4 0]           463.426455
[0 0 0 1 0 2]          4277.619516
[0 0 0 1 1 0]         21264.254862
[0 0 0 1 1 2]           444.131789
[0 0 0 1 1 4]          3140.137544
[0 0 0 1 2 0]         15666.762364
[0 0 0 1 2 2]          5187.853172
[0 0 0 1 3 0]          3284.199296
[0 0 0 1 3 2]          2554.715551
[0 0 0 1 4 0]          2960.387858
[0 0 0 2 0 0]         31402.651686
[0 0 0 2 1 0]         15666.762364
[0 0 0 2 1 2]          5187.853172
[0 0 0 2 2 0]         10811.679136
[0 0 0 2 2 2]          3057.234950
[0 0 0 2 3 0]          9833.843273
[0 0 0 3 1 0]          3284.199296
[0 0 0 3 1 2]          2554.715551
[0 0 0 3 2 0]          9833.843273
[0 0 0 4 0 0]           463.426455
[0 0 0 4 1 0]          2960.387858
[0 0 1 0 1 2]           159.596697
[0 0 1 0 1 4]           877.988636
[0 0 1 0 2 2]          2130.448208
[0 0 1 0 3 0]       